---
sudo: false
before_install:
  - export HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
  - git config --global user.name "Dist Zilla Plugin TravisCI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
  - cpanm --quiet --notest Dist::Zilla
  - dzil authordeps | grep -ve '^\W' | xargs -n 5 -P 10 cpanm --quiet --notest
  - dzil listdeps | grep -ve '^\W' | cpanm --quiet --notest
language: perl
perl:
  - '5.16'
script:
  - dzil smoke --release --author
